# This file was generated by GoReleaser. DO NOT EDIT.
cask "freda" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "28957685647c8c399de55c54d58cc7dfae18e00291500a84de14d4ebce7ca56a"
      url "https://github.com/agrechin/freda-releases/releases/download/v#{version}/freda_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_intel do
      sha256 "86220a48491b6514236c381a54160690d815f44f98cac087a0a7e0fcdb645034"
      url "https://github.com/agrechin/freda-releases/releases/download/v#{version}/freda_#{version}_linux_amd64.tar.gz"
    end
  end

  name "freda"
  desc "Archive Fireflies.ai meeting transcripts to Google Cloud Storage as Markdown."
  homepage "https://github.com/agrechin/freda-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "freda"

  # No zap stanza required
end
